name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - uses: actions/checkout@v5

      - name: Restore Dependencies (ubuntu)
        run: |
          for project in tests/**/*.csproj; do
            dotnet restore "$project"
          done
    
      - name: Build (ubuntu)
        run: |
          for project in tests/**/*.csproj; do
            dotnet build "$project" --configuration Release --no-restore
          done

      - name: Test (ubuntu)
        run: |
          for project in tests/**/*.csproj; do
            dotnet test "$project" --configuration Release --no-build
          done

  test-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore Dependencies (windows)
        run: |
          Get-ChildItem -Path tests -Filter *.csproj -Recurse | ForEach-Object {
            dotnet restore $_.FullName
          }
    
      - name: Build (windows)
        run: |
          Get-ChildItem -Path tests -Filter *.csproj -Recurse | ForEach-Object {
            dotnet build $_.FullName --configuration Release --no-restore
          }

      - name: Test (windows)
        run: |
          Get-ChildItem -Path tests -Filter *.csproj -Recurse | ForEach-Object {
            dotnet test $_.FullName --configuration Release --no-build
          }
